FROM debian:buster as builder

RUN apt-get -q update
RUN apt-get install -yq wget apt-transport-https gnupg2
RUN wget --quiet https://epicsdeb.bnl.gov/debian/repo-key.pub -O - \
                        | apt-key add -
RUN echo "deb https://epicsdeb.bnl.gov/debian/ buster main contrib" \
                        | tee /etc/apt/sources.list.d/nsls2.list
RUN apt-get update

RUN apt-get install -yq build-essential git

# see https://itnext.io/building-docker-images-from-private-git-repositories-using-ssh-login-433edf5a18f2
COPY lbl_gitlab_key .
RUN eval $(ssh-agent) && \
    ssh-add lbl_gitlab_key && \
    ssh-keyscan -H gitlab.lbl.gov >> /etc/ssh/ssh_known_hosts && \
    git clone git@gitlab.lbl.gov:drivers/FEED.git /opt/FEED

RUN apt-get install -yq epics-dev epics-busy-dev \
                        epics-asyn-dev epics-autosave-dev \
                        epics-caputlog-dev epics-iocstats-dev \
                        epics-seq-dev
RUN apt-get install -yq libfftw3-dev zlib1g-dev
RUN apt-get install -yq python python3 python-numpy python3-numpy
RUN apt-get install -yq vim

COPY RELEASE.local /opt/FEED/configure
RUN cd /opt/FEED && make -k || make -k || make -k

#
#
#FROM debian:buster
#
#COPY --from=builder /opt/FEED /opt/FEED
#RUN chmod 755 /opt/FEED/iocBoot/iochires/st.cmd
#
#EXPOSE 5065/tcp 5064/tcp
#EXPOSE 5065/udp 5064/udp
#
#ENTRYPOINT ["/opt/FEED/iocBoot/iochires/st.cmd"]
